# Generated by Django 3.1 on 2023-01-20 20:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='languages_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('JV', 'Java'), ('JS', 'Javascript'), ('CS', 'Css'), ('HT', 'Html'), ('RC', 'React'), ('C+', 'C++'), ('C#', 'C#')], default=False, max_length=23),
        ),
    ]
