# Generated by Django 3.1 on 2023-01-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230121_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='languages_choice',
            field=models.SlugField(choices=[('Python', '1'), ('Java', '2'), ('Javascript', '3'), ('Css', '4'), ('Html', '5'), ('React', '6'), ('C++', '7'), ('C#', '8')], default=False),
        ),
    ]
