# Generated by Django 3.1 on 2023-01-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_languages_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='languages_choice',
            field=models.SlugField(choices=[('PY', 'Python'), ('JV', 'Java'), ('JS', 'Javascript'), ('CS', 'Css'), ('HT', 'Html'), ('RC', 'React'), ('C+', 'C++'), ('C#', 'C#')], default=False),
        ),
    ]
